# Welcome to BasicCustomShops (BCS) config!

# Message prefix for messages sent by this plugin.
message-prefix: "&7[&a&lShop&2&lManager&7]" # Only can use Minecraft color codes.

# Shop Customization
shop-title: "&a&lShop"